name: test for chocoham's blog

on: [push, pull_request]

jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy at vercel
        uses: dkershner6/vercel-set-env-action@v1
        with:
          vercel-token: ${{ secretes.VERCEL_TOKEN }}
          projectName: chocoham

      - name: install packages
        run: yarn install

      - name: build page
        run: yarn run build
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DEV_URL: ${{ secrets.DEV_URL }}
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: doTest
        run: yarn run test